package rockabilly.coarsegrind.examples.simple;

import rockabilly.coarsegrind.core.Global;
import rockabilly.coarsegrind.core.TestCase;
import rockabilly.coarsegrind.core.TestStatus;

public class SimpleExample2 extends TestCase
{

	@Override
	public String getTestCaseDetailedDescription()
	{
		return "This is the detailed description for SimpleExample2.  Use this field to describe what the test does and what its pass criteria are. Commas, \tTabs, \rCarriage Returns, \nLine Feeds, and \fForm Feed chars will be filtered out.";
	}

	@Override
	public void performTest()
	{
		// This would be where you actually perform the test.  What a surprise, huh?
		// If setup fails, it will NOT be run.
		
		int percentSetup = 100;
		checkPrerequisite("Verifying that everything is setup.", percentSetup == 100);
		
		// Coarse Grind does not interrupt the test if something fails.
		// This is by-design to support multiple points-of-failure.
		// If inconclusive or failing status makes it pointless to proceed, you must explicitly enforce that.
		if (this.getOverallStatus() != TestStatus.Inconclusive)
		{
			// You should log every little thing the test does.  That lessens the chance of needing to re-run when a bug happens.
			Global.Log.message("Calling doSomethingOne()");
			//int return1 = doSomethingOne();
			int return1 = 42;
			
			Global.Log.message("Calling doSomethingTwo()");
			//int return2 = doSomethingTwo();
			int return2 = 42; 
	
			Global.Log.message("Calling doSomethingThree()");
			//doSomethingThree();
			
			Global.Log.message(Global.Log.getInfoIcon(), "This message has an info icon");
			Global.Log.message(Global.Log.getWarningIcon(), "This message has a warning icon");
			
			// The line below should make this test failing.
			// The test subject will now be failing unless something makes it inconclusive, as SimpleExample3 will.
			checkPassCriterion("Everything adds up nicely.", return1 + return2 == 99);
		}
	}

	@Override
	public boolean cleanup()
	{
		// This will ALWAYS be run, even if setup failed.
		return true;
	}

	@Override
	public String getIdentifier()
	{
		// This can be anything but is typically a number generated by a test case management system.
		// It is generally easier to say that "Test ST7 failed" than "The string-based selection upper limit test failed."
		return "ST2";
	}

	@Override
	public String getName()
	{
		// This should be a human-readable name that describes the test in-brief
		return "Sample Test TWO";
	}

	@Override
	public boolean setup()
	{
		// Perform any test case specific setup.
		// If this does not return true, performTest() will never be run.
		// You may wish to make an abstract class that extends TestCase.
		// Lots of testcases could extend that and share the same setup(),
		// cleanup(), and other common methods.
		return true;
	}

	@Override
	public String[] getTestSuiteMemberships() {
		return new String[] {"Simple", "All"};
	}

	@Override
	public String[] getTestCategoryMemberships() {
		return new String[] {"Example"};
	}

}
